{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fmesher
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fmesher_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fmesher/fmesher_{{ version }}.tar.gz
  sha256: ed5ddc18ddb1a4abfa61fe3f35e7310d459a19e992bd7a04875a2f2c1f54ba4e

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-lifecycle
    - r-matrix
    - r-rcpp
    - r-rlang
    - r-sf
    - r-sp >=1.6_1
    - r-tibble
    - r-withr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-dplyr
    - r-lifecycle
    - r-matrix
    - r-rcpp
    - r-rlang
    - r-sf
    - r-sp >=1.6_1
    - r-tibble
    - r-withr

test:
  commands:
    - $R -e "library('fmesher')"           # [not win]
    - "\"%R%\" -e \"library('fmesher')\""  # [win]

about:
  home: https://inlabru-org.github.io/fmesher/
  dev_url: https://github.com/inlabru-org/fmesher
  license: MPL-2.0
  summary: Generate planar and spherical triangle meshes, compute finite element calculations for 1- and 2-dimensional flat and curved manifolds with associated basis function spaces, methods for lines and polygons, and transparent handling of coordinate reference systems and coordinate transformation, including 'sf' and
    'sp' geometries. The core 'fmesher' library code was originally part of the 'INLA' package, and implements parts of "Triangulations and Applications" by Hjelle and Daehlen (2006) <doi:10.1007/3-540-33261-8>.
  license_family: OTHER
  license_file:
    - MPL-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
