{% set version = "0.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-fmesher
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fmesher_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fmesher/fmesher_{{ version }}.tar.gz
  sha256: 2230b2c01b05ef61bc5ae7636bbbc792c04d43b345138d30e792a8dbbdc1979d

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-lifecycle
    - r-matrix
    - r-rcpp
    - r-rlang
    - r-sf
    - r-sp >=1.6_1
    - r-tibble
    - r-withr
  run:
    - r-base
    - r-dplyr
    - r-lifecycle
    - r-matrix
    - r-rcpp
    - r-rlang
    - r-sf
    - r-sp >=1.6_1
    - r-tibble
    - r-withr

test:
  commands:
    - $R -e "library('fmesher')"           # [not win]
    - "\"%R%\" -e \"library('fmesher')\""  # [win]

about:
  home: https://inlabru-org.github.io/fmesher/
  dev_url: https://github.com/inlabru-org/fmesher
  license: MPL-2.0
  summary: Generate planar and spherical triangle meshes, compute finite element calculations for 1- and 2-dimensional flat and curved manifolds with associated basis function spaces, methods for lines and polygons, and transparent handling of coordinate reference systems and coordinate transformation, including 'sf' and
    'sp' geometries. The core 'fmesher' library code was originally part of the 'INLA' package, and implements parts of "Triangulations and Applications" by Hjelle and Daehlen (2006) <doi:10.1007/3-540-33261-8>.
  license_family: OTHER
  license_file:
    - MPL-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
